node {
    
	

    env.AWS_ECR_LOGIN=true
    def newApp
    def registry = 'ragav1997/test-practice'
    def registryCredential = 'docker-hub'
	
	
	stage('Git') {
		git 'https://github.com/ragavm24/DockerizeJenkins.git'
	}
	stage('Build') {
	        sh 'whoami'
            sh 'mvn -B -DskipTests clean package'
    }
    stage('Test') {
            sh 'mvn test'
    }
    stage('Building image') {
        //docker.withRegistry( '', registryCredential ) {
		    def buildName = registry + ":$BUILD_NUMBER"
			newApp = docker.build buildName
			//newApp.push()
    }
	stage('Registring image') {
        docker.withRegistry( 'https://' + registry, registryCredential ) {
    		newApp.push 'latest2'
        }
	}
    stage('Removing image') {
        sh "docker rmi $registry:$BUILD_NUMBER"
        sh "docker rmi $registry:latest"
    }
    
}
